spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/trading_payment_db
    username: postgres
    password: rahul@1995
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.instrumentation.tracing.enabled: true
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.trading.paymentservice.dto.external.OrderResponseDto
        spring.instrumentation.tracing.enabled: true




server:
  port: 8084


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans